### ISSUE TITLE
[bug] Sequelize.sync() 재시작했을 때 model 생성 과정에서 오류 발생

### ISSUE THREAD

**Issue by chaeinP** [innovationacademy-kr/slabs-munetic#46]
둘 중 하나를 참고하여 작성할 것. bug, feat 외에 commit 타입을 선택해서 작성 가능합니다.

### 발견 일시
21/12/12(일) 오후 4:00

### 증상
Sequelize.sync(force:true) 상황에서 express 서버 재시작했을 때 models 생성에서 오류가 발생해 테이블이 생성이 되지 않는 이슈가 있었습니다. 

### 발생 위치 (optional)
munetic_express

### 재현 방법
현재 커밋에서 /munetic_database/my.cnf 에서 lower_case_table_names  = 2 로 바꾸고 docker를 재시작해서 docker-compose를 실행시키면 다음의 에러를 확인하실 수 있습니다.
```
munetic_express    |   original: SqlError: (conn=7, no: 1146, SQLState: 42S02) Table 'munetic.category' doesn't exist
munetic_express    |   sql: SHOW INDEX FROM `Category` - parameters:[]
munetic_express    |       at Object.module.exports.createError (/munetic_express/node_modules/mariadb/lib/misc/errors.js:61:10)
munetic_express    |       at PacketNodeEncoded.readError (/munetic_express/node_modules/mariadb/lib/io/packet.js:505:19)
munetic_express    |       at Query.readResponsePacket (/munetic_express/node_modules/mariadb/lib/cmd/resultset.js:46:28)
munetic_express    |       at PacketInputStream.receivePacketBasic (/munetic_express/node_modules/mariadb/lib/io/packet-input-stream.js:104:9)
munetic_express    |       at PacketInputStream.onData (/munetic_express/node_modules/mariadb/lib/io/packet-input-stream.js:169:20)
munetic_express    |       at Socket.emit (node:events:390:28)
munetic_express    |       at Socket.emit (node:domain:475:12)
munetic_express    |       at addChunk (node:internal/streams/readable:315:12)
munetic_express    |       at readableAddChunk (node:internal/streams/readable:289:9)
munetic_express    |       at Socket.Readable.push (node:internal/streams/readable:228:10) {
munetic_express    |     text: "Table 'munetic.category' doesn't exist",
munetic_express    |     sql: 'SHOW INDEX FROM `Category`',
munetic_express    |     fatal: false,
munetic_express    |     errno: 1146,
munetic_express    |     sqlState: '42S02',
munetic_express    |     code: 'ER_NO_SUCH_TABLE',
munetic_express    |     parameters: undefined
munetic_express    |   },
munetic_express    |   sql: 'SHOW INDEX FROM `Category`',
munetic_express    |   parameters: undefined
munetic_express    | }
```

### 스크린샷

---

**Comment by chaeinP** [comment]
express 서버를 재시작할 때 기존에 생성되어있는 테이블이 있으면 삭제하고 다시 Create 명령어를 실행하는데 이 때 `SHOW INDEX FROM `Category``라는 명령어가 추가로 실행됩니다. 이 과정에서 테이블이름을 `text: "Table 'munetic.category' doesn't exist",`소문자로 취급해 대문자로 시작하는 Category 테이블을 찾지 못해 에러가 발생했습니다. Docker 내부 MariaDB설정에서 테이블 대소문자 설정을 담당하는 lower_case_table_names 설정을 2에서 1로 바꿔주니 더이상 테이블에서 대소문자를 구분하지 않아 에러가 해결될 수 있었습니다.

munetic_database/db/my.cnf 파일을 추가해 db 도커 컨테이너의 my.cnf파일과 마운트 시켜 lower_case_table_names  = 2를 1로 설정하였고 관련해 마운트 설정이 compose.yaml에 추가되었습니다. (by jolim)
